services:
  db: # ← ЭТОТ блок обязателен
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: BookingSportsDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD:-553253}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  api:
    build: ./BookingSports
    env_file: .env
    depends_on:
      db:
        condition: service_healthy # ждём “зелёную” БД
    ports:
      - "5000:8080"

  web:
    build: ./next-sport-app
    depends_on: [api]
    ports:
      - "3000:3000"

volumes:
  pgdata:
