version: "3.9"

services:
  api:
    build:
      context: ./BookingSports
    env_file: .env
    ports:
      - "5000:80"

  web:
    build:
      context: ./next-sport-app
    depends_on:
      - api
    ports:
      - "3000:3000"
